version: "3.8"

services:
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS:
        -ifNotExists 
        -tcp 
        -tcpAllowOthers 
        -tcpPort 1521
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
    platform: linux/amd64

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  musinsa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:1521/demo
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db
      - redis
    platform: linux/amd64
