spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql