spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://db:1521/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      encoding: utf-8
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: redis
    port: 6379