DROP TABLE IF EXISTS TB_PRODUCT;
DROP TABLE IF EXISTS TB_CATEGORY;
DROP TABLE IF EXISTS TB_BRAND;

CREATE TABLE TB_CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL,
    NAME_EN VARCHAR(15) NOT NULL
);

CREATE TABLE TB_BRAND (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(3) NOT NULL
);

CREATE TABLE TB_PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    BRAND_ID INT NOT NULL,
    PRICE INTEGER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY(ID),
    FOREIGN KEY (BRAND_ID) REFERENCES TB_BRAND(ID)
);